var annotated_dup =
[
    [ "Application", "classApplication.html", "classApplication" ],
    [ "Book", "classBook.html", "classBook" ],
    [ "Config", "structConfig.html", "structConfig" ],
    [ "CSVWriter", "classCSVWriter.html", "classCSVWriter" ],
    [ "Dashboard", "classDashboard.html", "classDashboard" ],
    [ "FeatureRecord", "structFeatureRecord.html", "structFeatureRecord" ],
    [ "FitOptions", "structFitOptions.html", "structFitOptions" ],
    [ "GMM", "classGMM.html", "classGMM" ],
    [ "GMMParams", "structGMMParams.html", "structGMMParams" ],
    [ "GMMResult", "structGMMResult.html", "structGMMResult" ],
    [ "Logger", "classLogger.html", "classLogger" ],
    [ "Market", "classMarket.html", "classMarket" ],
    [ "MarketSnapshot", "structMarketSnapshot.html", "structMarketSnapshot" ],
    [ "Order", "structOrder.html", "structOrder" ],
    [ "OrderEvent", "structOrderEvent.html", "structOrderEvent" ],
    [ "OrderTracker", "classOrderTracker.html", "classOrderTracker" ],
    [ "PriceLevel", "structPriceLevel.html", "structPriceLevel" ],
    [ "ReplayController", "classReplayController.html", "classReplayController" ],
    [ "ReplayEngine", "classReplayEngine.html", "classReplayEngine" ],
    [ "SessionStats", "structSessionStats.html", "structSessionStats" ],
    [ "SpreadPoint", "structSpreadPoint.html", "structSpreadPoint" ],
    [ "TradeExecution", "structTradeExecution.html", "structTradeExecution" ]
];